package kotnexlib

/**
 * Holds different language codes. Currently only the BCP 47 type [BCP47] , which is widely used on the internet.
 */
class Languages(val code: String, val language: String, val region: String, val description: String) {

    enum class BCP47(val code: String, val language: String, val region: String, val description: String) {
        ArabicSaudiArabia("ar-SA", "Arabic", "Saudi Arabia", "Arabic (Saudi Arabia)"),
        BengaliBangladesh("bn-BD", "Bangla", "Bangladesh", "Bangla (Bangladesh)"),
        BengaliIndia("bn-IN", "Bangla", "India", "Bangla (India)"),
        CzechCzechRepublic("cs-CZ", "Czech", "Czech Republic", "Czech (Czech Republic)"),
        DanishDenmark("da-DK", "Danish", "Denmark", "Danish (Denmark)"),
        GermanAustria("de-AT", "German", "Austria", "Austrian German"),
        GermanSwitzerland("de-CH", "German", "Switzerland", "\"Swiss\" German"),
        GermanGermany("de-DE", "German", "Germany", "Standard German (as spoken in Germany)"),
        GreekGreece("el-GR", "Greek", "Greece", "Modern Greek"),
        EnglishAustralia("en-AU", "English", "Australia", "Australian English"),
        EnglishCanada("en-CA", "English", "Canada", "Canadian English"),
        EnglishUnitedKingdom("en-GB", "English", "United Kingdom", "British English"),
        EnglishIreland("en-IE", "English", "Ireland", "Irish English"),
        EnglishIndia("en-IN", "English", "India", "Indian English"),
        EnglishNewZealand("en-NZ", "English", "New Zealand", "New Zealand English"),
        EnglishUnitedStates("en-US", "English", "United States", "US English"),
        EnglishSouthAfrica("en-ZA", "English", "South Africa", "English (South Africa)"),
        SpanishArgentina("es-AR", "Spanish", "Argentina", "Argentine Spanish"),
        SpanishChile("es-CL", "Spanish", "Chile", "Chilean Spanish"),
        SpanishColumbia("es-CO", "Spanish", "Columbia", "Colombian Spanish"),
        SpanishSpain("es-ES", "Spanish", "Spain", "Castilian Spanish (as spoken in Central-Northern Spain)"),
        SpanishMexico("es-MX", "Spanish", "Mexico", "Mexican Spanish"),
        SpanishUnitedStates("es-US", "Spanish", "United States", "American Spanish"),
        FinnishFinland("fi-FI", "Finnish", "Finland", "Finnish (Finland)"),
        FrenchBelgium("fr-BE", "French", "Belgium", "Belgian French"),
        FrenchCanada("fr-CA", "French", "Canada", "Canadian French"),
        FrenchSwitzerland("fr-CH", "French", "Switzerland", "\"Swiss\" French"),
        FrenchFrance("fr-FR", "French", "France", "Standard French (especially in France)"),
        HebrewIsrael("he-IL", "Hebrew", "Israel", "Hebrew (Israel)"),
        HindiIndia("hi-IN", "Hindi", "India", "Hindi (India)"),
        HungarianHungary("hu-HU", "Hungarian", "Hungary", "Hungarian (Hungary)"),
        IndonesianIndonesia("id-ID", "Indonesian", "Indonesia", "Indonesian (Indonesia)"),
        ItalianSwitzerland("it-CH", "Italian", "Switzerland", "\"Swiss\" Italian"),
        ItalianItaly("it-IT", "Italian", "Italy", "Standard Italian (as spoken in Italy)"),
        JapaneseJapan("jp-JP", "Japanese", "Japan", "Japanese (Japan)"),
        KoreanRepublicOfKorea("ko-KR", "Korean", "Republic of Korea", "Korean (Republic of Korea)"),
        DutchBelgium("nl-BE", "Dutch", "Belgium", "Belgian Dutch"),
        DutchTheNetherlands("nl-NL", "Dutch", "The Netherlands", "Standard Dutch (as spoken in The Netherlands)"),
        NorwegianNorway("no-NO", "Norwegian", "Norway", "Norwegian (Norway)"),
        PolishPoland("pl-PL", "Polish", "Poland", "Polish (Poland)"),
        PortugueseBrazil("pt-BR", "Portuguese", "Brazil", "Brazilian Portuguese"),
        PortuguesePortugal("pt-PT", "Portuguese", "Portugal", "European Portuguese (as written and spoken in Portugal)"),
        RomanianRomania("ro-RO", "Romanian", "Romania", "Romanian (Romania)"),
        RussianRussianFederation("ru-RU", "Russian", "Russian Federation", "Russian (Russian Federation)"),
        SlovakSlovakia("sk-SK", "Slovak", "Slovakia", "Slovak (Slovakia)"),
        SwedishSweden("sv-SE", "Swedish", "Sweden", "Swedish (Sweden)"),
        TamilIndia("ta-IN", "Tamil", "India", "Indian Tamil"),
        TamilSriLanka("ta-LK", "Tamil", "Sri Lanka", "Sri Lankan Tamil"),
        ThaiThailand("th-TH", "Thai", "Thailand", "Thai (Thailand)"),
        TurkishTurkey("tr-TR", "Turkish", "Turkey", "Turkish (Turkey)"),
        ChineseChina("zh-CN", "Chinese", "China", "Mainland China, simplified characters"),
        ChineseHongKong("zh-HK", "Chinese", "Hong Kong", "Hong Kong, traditional characters"),
        ChineseTaiwan("zh-TW", "Chinese", "Taiwan", "Taiwan, traditional characters"),

    }
}